Practica01/Practica01/Models/Acciones.cs
namespace Practica01.Models
{
    public class Acciones
    {
        public Double dato1 { get; set; }
        public Double dato2 { get; set; }

    }
}

Practica01/Practica01/Models/ErrorViewModel.cs
namespace Practica01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Practica01/Practica01/Models/Estudiantes.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Practica01.Models
{
    public class Estudiantes
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //[Required]
        public int id { get; set; }
        public string? name { get; set; }
        public string? lastName { get; set; }

    }
}

Practica01/Practica01/Controllers/EstudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Practica01.Models;
using Practica01.Services;
//Angel Gabirel Mnejivar Rivera
namespace Practica01.Controllers
{
    public class EstudentsController : Controller
    {

        private IEstudents Estudents;

        public EstudentsController(IEstudents estudents)
        {
            Estudents = estudents;
        }

        public IActionResult Delete(int id) 
        {
            Estudiantes es = new Estudiantes();
            es.id = id;
            Estudents.DeleteStudent(es);
            return RedirectToAction ("Index");
        }
        public IActionResult Load (int id)
        {
            Estudiantes es = new Estudiantes();
            es.id = id;
            var listadlistadoEstudiante = Estudents.loadInformation(es);
           return View(listadlistadoEstudiante);

        }

        public IActionResult actu(Estudiantes es) 
        {

            Estudents.UpdateStudent(es);
            return RedirectToAction("Index");

        }

        public IActionResult Guardar()
        {



            return View();
        }

        public IActionResult Save(Estudiantes es)
        {

            Estudents.AddStudent(es);
            return RedirectToAction("Index");

        }


        public IActionResult Index()
        {
            Estudiantes es= new Estudiantes();
            //es.id = 1;
            //es.name = "Angell";
            //es.lastName = "Gabriel2";
            //Estudents.AddStudent(es); //para agregar
            //Estudents.DeleteStudent(es);//eliminar
            //Estudents.UpdateStudent(es); //actualizar ya ingresado
            //Estudents.GetAll();
            var listar = Estudents.GetAll();

            return View(listar);
        }
    }
}

Practica01/Practica01/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Practica01.Bussines;
using Practica01.Models;
using System.Diagnostics;

namespace Practica01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //importante sin una action no hay vista y viseversa
        public IActionResult Ejercicio(Acciones acciones)
        {
            //if (acciones.dato1 > 10 || acciones.dato2 > 10)
            //{
            //    return View("ErrornoMayores");
            //}

            //double resultado = acciones.dato1 + acciones.dato2;
            //ViewBag.datoN1V = acciones.dato1;
            //ViewBag.datoN2V = acciones.dato2;
            //ViewBag.variableaenviar = resultado;
            Operaciones op = new Operaciones();
            double resultado = op.Ejercicio(acciones);
            ViewBag.variableaenviar = resultado;
            return View();
        }
        public IActionResult ErrornoMayores()
        {
            return View();
        }
        public IActionResult resta(Acciones acciones)
        {
            //if (acciones.dato1 > 10 || acciones.dato2 > 10)
            //{
            //    return View("ErrornoMayores");
            //}

            //double resultado = acciones.dato1 - acciones.dato2;
            //ViewBag.datoR1V = acciones.dato1;
            //ViewBag.datoR2V = acciones.dato2;
            //ViewBag.variableaenviar = resultado;
            Operaciones op = new Operaciones();

            double resultado = op.resta(acciones);
            ViewBag.variableaenviar = resultado;
            return View();

        }
        public IActionResult Multiplicacion(Acciones acciones)
        {
            //    if (acciones.dato1 > 10 || acciones.dato2 > 10)
            //    {
            //        return View("ErrornoMayores");
            //    }

            //    double resultado = acciones.dato1 * acciones.dato2;
            //    ViewBag.datoM1V = acciones.dato1;
            //    ViewBag.datoM2V = acciones.dato2;
            //    ViewBag.variableaenviar = resultado;


            //OBJETO DE NEGOCIO
            Operaciones op = new Operaciones();

            double resultado = op.Multiplicacion(acciones);
            ViewBag.variableaenviar = resultado;
            return View();

        }
        public IActionResult Division(Acciones acciones)
        {
            //    if (acciones.dato1 > 10 || acciones.dato2 > 10)
            //    {
            //        return View("ErrornoMayores");
            //    }

            //    double resultado = acciones.dato1 / acciones.dato2;
            //    ViewBag.datoD1V = acciones.dato1;
            //    ViewBag.datoD2V = acciones.dato2;
            //    ViewBag.variableaenviar = resultado;

            Operaciones op = new Operaciones();

            double resultado = op.Division(acciones);
            ViewBag.variableaenviar = resultado;
            return View();

        }
        [HttpGet]
        public IActionResult PeticionTypeGet() 
        {

            return View();
        }

       
        public IActionResult SecondPage() 
        {


            return View();
        }



    }
}

Practica01/Practica01/Views/Estudents/Guardar.cshtml
@model Practica01.Models.Estudiantes
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="Estudents" asp-action="actu"> 
    
    <label>Name</label>
    <input type="text" asp-for="name" />
    <label>Last name</label>
    <input type="text" asp-for="lastName" />
    <button>Update</button>
</form>

Practica01/Practica01/Views/Estudents/Index.cshtml
@model List<Practica01.Models.Estudiantes>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

  
    <a class="btn btn-success" href="@Url.Action("Guardar","Estudents")">Add</a>
    @Html.ActionLink("Save","Guardar","Estudents",new{@class="btn btn-danger"})

<table  class="table table-dark table-striped" id= "tablaEst">
    <thead>
        <tr>
             
            <th>Name</th>
            <th>Last Name</th>
            <th>Acciones</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach(var iterar in Model)
        {
            <tr>
                
                <td>@iterar.name </td>
                <td>@iterar.lastName </td>
                <td>@Html.ActionLink("Delete","Delete",new{id=@iterar.id},new{@class="btn btn-danger"} )
                 @Html.ActionLink("Update","Load",new{id=@iterar.id},new{@class="btn btn-warning"} )</td>

            </tr>
        }
    </tbody>

</table>

@section scripts{
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
        alert ('ready load');
        

        var tabla = $('#tablaEst').DataTable();

        }
        );

    </script>
}

Practica01/Practica01/Views/Estudents/Load.cshtml
@model Practica01.Models.Estudiantes
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form asp-controller="Estudents" asp-action="actu">
    <label>id</label>
    <input type="text" asp-for="id" />
      <label>nombre</label>
    <input type="text" asp-for="name" />
      <label>last name</label>
    <input type="text" asp-for="lastName" />

    <button>Update</button>

</form>

Practica01/Practica01/Views/Estudents/Save.cshtml
@model Practica01.Models.Estudiantes
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="Students" asp-action="actu"> 
    
    <label>Name</label>
    <input type="text" asp-for="name" />
    <label>Last name</label>
    <input type="text" asp-for="lastName" />
    <button>Update</button>
</form>

Practica01/Practica01/Views/Home/Division.cshtml
@model Practica01.Models.Acciones
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Division</h1>

<div class="color">
<form asp-controller="Home" asp-action="Division"> 
    <div class="card"> 
<label> Dato1</label>

    @if (ViewBag.datoD1V==0)
    {
        
        <input type="number" asp-for="dato1" placeholder="Coloca el primer numero"  class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato1" placeholder="Coloca el primer numero"  class="form-control"  min="0" max="10"/>

    }
    <label> Dato2</label>
      @if (ViewBag.datoD2V==0)
    {
        
        <input type="number" asp-for="dato2" placeholder="Coloca el primer numero" class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato2" placeholder="Coloca el primer numero"  class="form-control"min="0" max="10"/>

    }


<button  class="btn btn-warning">Calcular</button>
<label> resultado</label>
<label> @ViewBag.variableaenviar</label>
</div>
</form>

</div>

Practica01/Practica01/Views/Home/Ejercicio.cshtml
@model Practica01.Models.Acciones

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Suma </h1>

<div class="color">
<form asp-controller="Home" asp-action="Ejercicio"> 
    <div class="card"> 
<label> Dato1</label>

    @if (ViewBag.datoN1V==0)
    {
        
        <input type="number" asp-for="dato1" placeholder="Coloca el primer numero"  class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato1" placeholder="Coloca el primer numero"  value="@ViewBag.datoN1V" class="form-control"/>

    }
    <label> Dato2</label>
      @if (ViewBag.datoN2V==0)
    {
        
        <input type="number" asp-for="dato2" placeholder="Coloca el primer numero"  class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato2" placeholder="Coloca el primer numero" value="@ViewBag.datoN2V" class="form-control"min="0" max="10"/>

    }






<button  class="btn btn-danger">Calcular</button>
<label> resultado</label>
<label> @ViewBag.variableaenviar</label>
</div>
</form>

</div>

Practica01/Practica01/Views/Home/ErrornoMayores.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Error los numeros son mayores</h1>

Practica01/Practica01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<a href="SecondPage">Ir a pajina principal </a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SecondPage">Ejamplo peticion Get</a>

Practica01/Practica01/Views/Home/Multiplicacion.cshtml
@model Practica01.Models.Acciones

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Multiplicacion</h1>

<div class="color">
<form asp-controller="Home" asp-action="Multiplicacion"> 

    <div class="card"> 
<label> Dato1</label>

    @if (ViewBag.datoM1V==0)
    {
        
        <input type="number" asp-for="dato1" placeholder="Coloca el primer numero"   class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato1" placeholder="Coloca el primer numero"  value="@ViewBag.datoM1V" class="form-control"/>

    }
    <label> Dato2</label>
      @if (ViewBag.datoM2V==0)
    {
        
        <input type="number" asp-for="dato2" placeholder="Coloca el primer numero"   class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato2" placeholder="Coloca el primer numero"  value="@ViewBag.datoM2V" class="form-control"min="0" max="10"/>

    }






<button  class="btn btn-dark">Calcular</button>
<label> resultado</label>
<label> @ViewBag.variableaenviar</label>
</div>
</form>

</div>

Practica01/Practica01/Views/Home/PeticionTypeGet.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a>Soy la peticion Get</a>

Practica01/Practica01/Views/Home/SecondPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Practica01/Practica01/Views/Home/View.cshtml
@model Practica01.Models.Acciones

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>Acciones</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="dato1" class="control-label"></label>
                <input asp-for="dato1" class="form-control" />
                <span asp-validation-for="dato1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dato2" class="control-label"></label>
                <input asp-for="dato2" class="form-control" />
                <span asp-validation-for="dato2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practica01/Practica01/Views/Home/resta.cshtml
@model Practica01.Models.Acciones

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Resta</h1>

<div class="color">
<form asp-controller="Home" asp-action="resta"> 
    <div class="card"> 
<label> Dato1</label>

    @if (ViewBag.datoR1V==0)
    {
        
        <input type="number" asp-for="dato1" placeholder="Coloca el primer numero"   class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato1" placeholder="Coloca el primer numero" value="@ViewBag.datoR1V" class="form-control"/>

    }
    <label> Dato2</label>
      @if (ViewBag.datoR2V==0)
    {
        
        <input type="number" asp-for="dato2" placeholder="Coloca el primer numero"   class="form-control" min="0" max="10"/>

    }else{
    
         <input type="number" asp-for="dato2" placeholder="Coloca el primer numero"  value="@ViewBag.datoR2V" class="form-control"min="0" max="10"/>

    }






<button  class="btn btn-success">Calcular</button>
<label> resultado</label>
<label> @ViewBag.variableaenviar</label>
</div>
</form>

</div>

Practica01/Practica01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practica01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PeticionTypeGet">Ejamplo peticion Get</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Ejercicio">Suma</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="resta">Resta</a>
                        </li>
                          </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Multiplicacion">Multiplicacion</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Division">Division</a>
                        </li>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SecondPage">Second Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Practica01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>